- project:
    templates:
      - build-openstack-sphinx-docs
    check:
      jobs:
        - openstack-tox-pep8
    gate:
      jobs:
        - openstack-tox-pep8
    post:
      jobs:
        - publish-openstack-contributor-guide
